name: Build LingLink Frontend

on:
  push:
    branches: [ "cicd" ]
  pull_request:
    branches: [ "cicd" ]

jobs:
  build_test:
    name: Build LingLink Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Use Node.js 20.11.1
      uses: actions/setup-node@v3
      with:
        node-version: 20.11.1
        cache: 'npm'

    - name: Run Install
      uses: borales/actions-yarn@v4
      with:
        cmd: install --frozen-lockfile # will build `yarn build` command

    - name: Run build
      uses: borales/actions-yarn@v4
      with:
        cmd: build # will build `yarn build` command